

# Data file generated by postprocess_ARM_pilots_results.R
arm_pilots_env <- LoadIntoEnvironment(
    file.path(data_path, "ARM", "arm_pilots_results_original_data_121222.Rdata"))


param_names <- c(
    "offset"="\\mu",
    "log_resid"="\\log \\sigma_y",
    "log_scenario"="\\log \\sigma_{scn}",
    "log_group"="\\log \\sigma_{grp}",
    "log_rs_diff"="\\log \\sigma_y - \\log \\sigma_{scn}",
    "log_rg_diff"="\\log \\sigma_y - \\log \\sigma_{grp}",
    "log_sg_diff"="\\log \\sigma_{scn} - \\log \\sigma_{grp}"
)


method_names <- c(
    "bayes"="Bayes",
    "ij"="IJ",
    "bootstrap"="Boot"
)

arm_pilots_env$plot_df <-
    arm_pilots_env$save_list$plot_df %>%
    filter(row_variable %in% !!names(param_names)) %>%
    mutate(method_name=method_names[method],
           param_name=factor(param_names[row_variable])) %>%
    filter(row_variable %in%
               c("log_rs_diff", "log_rg_diff", "log_sg_diff")) %>%
    mutate(se_se=bayesijlib::ConvertCovSEToSESE(
        x_cov=cov, x_cov_se=cov_se,
        n=arm_pilots_env$save_list$num_exch_obs)) %>%
    mutate(method=recode(method, bootstrap="boot"))


stopifnot(!any(is.na(arm_pilots_env$plot_df$param_name)))
stopifnot(!any(is.na(arm_pilots_env$plot_df$method_name)))
levels(arm_pilots_env$plot_df$param_name) <-
    TeX(sprintf("$%s$", levels(arm_pilots_env$plot_df$param_name)))
