# Data file generated by postprocess_ARM_results.R
arm_env <- LoadIntoEnvironment(
    file.path(data_path, "ARM", "arm_results_original_data_061721.Rdata"))

# Set shared parameters for the z statistic thresholding.
p_threshold <- 0.1
z_threshold <- qnorm(1 - p_threshold / 2)
